import os
os.system("pwd")
#os.system("rm -rf resnet50_1*.modeparams")
os.system("rm -rf resnet50_2*.modeparams")
os.system("rm -rf resnet50_3*.modeparams")
os.system("rm -rf resnet50_4*.modeparams")
os.system("rm -rf resnet50_5*.modeparams")
os.system("rm -rf resnet50_6*.modeparams")
os.system("rm -rf resnet50_7*.modeparams")
os.system("rm -rf resnet50_8*.modeparams")
os.system("rm -rf resnet50_9*.modeparams")
os.system('cp ./resnet50_268.modeparams /content/drive/MyDrive/trainedModes/resnet18End_95.modeparams')
os.system('cp ./resnet50_268.modeparams ./resnet18End.modeparams')
os.system('cp ./resnet50_268.modeparams ./resnet50End.modeparams')
